FROM debian:stable-slim

ENV BITCOIN_VERSION 0.18.1
ENV BITCOIN_DIR /home/bitcoin
ENV BITCOIN_DATA ${BITCOIN_DIR}/.bitcoin
ENV BITCOIN_BIN ${BITCOIN_DIR}/bitcoin-${BITCOIN_VERSION}/bin
ENV PATH ${BITCOIN_BIN}:$PATH

RUN apt-get -y update  && \
    apt-get -y upgrade && \
    apt-get install -y wget ca-certificates gosu gnupg tor && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN set -ex && \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 01EA5486DE18A882D4C2684590C8019E36C2E964 && \
    wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-arm-linux-gnueabihf.tar.gz && \
    wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/SHA256SUMS.asc && \
    gpg --verify SHA256SUMS.asc && \
    grep " bitcoin-${BITCOIN_VERSION}-arm-linux-gnueabihf.tar.gz\$" SHA256SUMS.asc | sha256sum -c -

RUN useradd -r bitcoin && \
    mkdir -p ${BITCOIN_DIR} && \
    mkdir -p ${BITCOIN_DATA} && \
    chown -R bitcoin ${BITCOIN_DIR} && \
    tar -xzf *.tar.gz -C ${BITCOIN_DIR} && \
    rm *.tar.gz *.asc

WORKDIR ${BITCOIN_DIR}
COPY entrypoint.sh .
COPY bitcoin.conf ${BITCOIN_DATA}/bitcoin.conf

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8332 8333 18332 18333 18443 18444

CMD ["bitcoind"]
