FROM debian:stable-slim

ENV BITCOIN_VERSION 0.18.1
ENV BITCOIN_DIR /bitcoin
ENV BITCOIN_DATA ${BITCOIN_DIR}/.bitcoin
ENV PATH /bitcoin/bitcoin-${BITCOIN_VERSION}/bin:$PATH

RUN useradd -r bitcoin && \
    apt-get -y update  && \
    apt-get -y upgrade && \
    apt-get install -y wget ca-certificates gosu gnupg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN set -ex && \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 01EA5486DE18A882D4C2684590C8019E36C2E964 && \
    wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-arm-linux-gnueabihf.tar.gz && \
    wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/SHA256SUMS.asc && \
    gpg --verify SHA256SUMS.asc && \
    grep " bitcoin-${BITCOIN_VERSION}-arm-linux-gnueabihf.tar.gz\$" SHA256SUMS.asc | sha256sum -c -

RUN mkdir -p ${BITCOIN_DIR} && \
    mkdir -p ${BITCOIN_DATA} && \
    tar -xzf *.tar.gz -C /bitcoin && \
    rm *.tar.gz *.asc

COPY entrypoint.sh /entrypoint.sh
#EXPOSE 8332 8333 18332 18333 18443 18444

#CMD ["bitcoind"]

